name: invoapp
description: "App mock de facturas."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  go_router: ^16.3.0
  get_it: ^8.2.0
  json_annotation: ^4.9.0
  bloc: ^9.1.0
  cached_network_image: ^3.4.1
  intl: ^0.20.2
  flutter_secure_storage: ^9.2.4
  consts: ^3.0.0
  flutter_motionly: ^1.1.1
  dio: ^5.9.0
  envied: ^1.3.1
  animate_do: ^4.2.0
  animated_text_kit: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.7
  json_serializable: ^6.11.1
  build_runner: ^2.10.1
  flutter_gen_runner: ^5.12.0
  freezed: ^3.2.3
  flutter_launcher_icons: ^0.14.4
  freezed_lint: ^0.0.12
  envied_generator: ^1.3.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter_native_splash:
  color: "#010102"
  image: assets/splash.png
  android_12:
    image: assets/splash.png